- name: build blog
  shell: |
    cd /Users/alomerry/workspace/mix/blog
    pnpm install && pnpm install
    tar -zcvf /Users/alomerry/workspace/mix/blog/dist/blog.tar.gz -C /Users/alomerry/workspace/mix/blog/dist/ .
    scp -r /Users/alomerry/workspace/mix/blog/dist/blog.tar.gz root@alomerry.com:/tmp/
    ssh root@alomerry.com "rm -rf /root/apps/nginx/site/blog.alomerry.com/*; tar -zxvf /tmp/blog.tar.gz -C /root/apps/nginx/site/blog.alomerry.com/"
- name: build docs
  shell: |
    cd /Users/alomerry/workspace/mix/docs
    pnpm install && pnpm install
    tar -zcvf /Users/alomerry/workspace/mix/docs/.vitepress/dist/docs.tar.gz -C /Users/alomerry/workspace/mix/docs/.vitepress/dist/ .
    scp -r /Users/alomerry/workspace/mix/docs/.vitepress/dist/docs.tar.gz root@alomerry.com:/tmp/
    ssh root@alomerry.com "rm -rf /root/apps/nginx/site/docs.alomerry.com/*; tar -zxvf /tmp/docs.tar.gz -C /root/apps/nginx/site/docs.alomerry.com/"