- name: init workspace
  shell: |
    mkdir /root/apps/nginx/site/{{ item }}/ -p
    mkdir /root/apps/nginx/cert/{{ item }}/ -p
    touch /root/apps/nginx/cert/{{ item }}/privkey.pem
    touch /root/apps/nginx/cert/{{ item }}/fullchain.pem
  with_items:
    - proxy.alomerry.com
- name: copy nginx conf
  copy:
    src: conf/{{ item }}.conf
    dest: /root/apps/nginx/conf/{{ item }}.conf
  with_items:
    - proxy.alomerry.com
