version: '3'
services:
  umami:
    image: docker.umami.dev/umami-software/umami:mysql-v2.5.0
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_TYPE: mysql
      APP_SECRET: ${APP_SECRET}
    restart: always
    networks:
      - home_mysql

networks:
  home_mysql:
    name: mysql_home_mysql
    external: true