- name: init jenkins workspace
  shell: |
    mkdir /root/apps/jenkins/ -p
- name: copy docker compose
  copy:
    src: jenkins.yml
    dest: /root/apps/jenkins/docker-compose.yml
- name: copy docker file
  copy:
    src: dockerfile
    dest: /root/apps/jenkins/dockerfile
- name: copy sources
  copy:
    src: sources.list
    dest: /root/apps/jenkins/sources.list
- name: copy plugin
  copy:
    src: plugins.txt
    dest: /root/apps/jenkins/plugins.txt
- name: stop and restart jenkins # TODO add pull /usr/bin/docker compose -f /root/apps/jenkins/docker-compose.yml build
  shell: |
    /usr/bin/docker compose -f /root/apps/jenkins/docker-compose.yml down
    /usr/bin/docker compose -f /root/apps/jenkins/docker-compose.yml up -d
