- name: forward ipv4
  shell: |
    cat <<EOF | tee /etc/modules-load.d/k8s.conf
    overlay
    br_netfilter
    EOF
    modprobe overlay
    modprobe br_netfilter
    cat <<EOF | tee /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    net.ipv4.ip_forward                 = 1
    EOF
    sysctl --system
- name: set containerd config
  copy:
    src: "containerd-conf.toml"
    dest: /etc/containerd/config.toml
- name: reload containerd
  shell: systemctl restart containerd
