apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-pv-docs
  labels:
    service: tekton
    project: docs
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /mnt/nvme0n1p1/tekton/docs
    server: 192.168.31.2
  persistentVolumeReclaimPolicy: Retain
---