- name: check frp exists
  ansible.builtin.stat:
    path: "/root/apps/frp_0.51.1_linux_amd64"
  register: basedir_stat
- name: download frp bin
  shell: mkdir /root/apps -p && wget -P /root/apps/ https://ghproxy.com/https://github.com/fatedier/frp/releases/download/v0.51.1/frp_0.51.1_linux_amd64.tar.gz
  when: not (basedir_stat.stat.exists and basedir_stat.stat.isdir)
- name: extract frp tar tar -xf archive.tar -C /home/myfreax/files
  shell: rm -rf /root/apps/frp_0.51.1_linux_amd64 && tar -xf /root/apps/frp_0.51.1_linux_amd64.tar.gz -C /root/apps
  when: not (basedir_stat.stat.exists and basedir_stat.stat.isdir)
- name: clean cache
  shell: rm -rf /root/apps/frp_0.51.1_linux_amd64.tar.gz /root/apps/frp_0.51.1_linux_amd64/frpc /root/apps/frp_0.51.1_linux_amd64/frpc.ini /root/apps/frp_0.51.1_linux_amd64/frpc_full.ini /root/apps/frp_0.51.1_linux_amd64/frps_full.ini /root/apps/frp_0.51.1_linux_amd64/LICENSE
- name: update frps ini
  copy:
    src: frps.ini
    dest: /root/apps/frp_0.51.1_linux_amd64/frps.ini
- name: update frps service
  copy:
    src: frps.service
    dest: /etc/systemd/system/frps.service
- name: enable and start frps service
  shell: systemctl enable frps.service && systemctl start frps.service
