- name: init uptime-kuma workspace
  shell: |
    mkdir /root/apps/uptime/ -p
- name: copy docker compose
  copy:
    src: uptime.yml
    dest: /root/apps/uptime/docker-compose.yml
- name: update uptime image and restart
  shell: |
    /usr/bin/docker compose -f /root/apps/uptime/docker-compose.yml pull
    /usr/bin/docker compose -f /root/apps/uptime/docker-compose.yml down
    /usr/bin/docker compose -f /root/apps/uptime/docker-compose.yml up -d --force-recreate
