version: '3'
services:
  mysql:
    restart: always
    image: mysql:8.0.34
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
      # - ./conf.cnf:/etc/mysql/my.cnf
      - ./source:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    networks:
      - home_mysql

networks:
  home_mysql:
    driver: bridge