version: '3'
services:
  vscode-web:
    build:
      context: .
      dockerfile: /home/alomerry-home/workspace/vps-home/frpc/vscode-web/Dockerfile
    # image: 'registry.cn-hangzhou.aliyuncs.com/alomerry/vscode-web:latest'
    container_name: vscode-web
    restart: always
    ports: 
      - '4000:8000' # 8000/8080/4000 vscode-web
    volumes:
      - '/media/alomerry-home/local-ssd/docker/vscode-web/workspace:/root/workspace'
      - '/home/alomerry-home/apps/vscode-web/extensions:/root/.vscode-server/extensions'