- name: 安装 nfs 相关包
  apt:
    name: '{{ item }}'
  with_items:
  - nfs-kernel-server
- name: 复制 nfs server 硬盘配置
  copy:
    src: nfs-server/exports
    dest: /etc/exports
    mode: 0644
- name: 启动 nfs server
  shell: |
    exportfs -arv
    systemctl stop nfs-kernel-server
    sleep 1
    systemctl start nfs-kernel-server
    # https://www.linuxprobe.com/ubuntu-configure-nfs.html
    # https://access.redhat.com/documentation/zh-cn/openshift_container_platform/4.3/html/storage/persistent-storage-using-nfs