import { arraySidebar } from "vuepress-theme-hope";

export const ioi = arraySidebar([
  "",
  {
    text: "算法笔记",
    collapsible: true,
    prefix: "algorithm/",
    children: [
      "kmp",
      "tail-recursion",
      "useful-cpp-lib",
    ],
  },
  {
    text: "数据结构",
    collapsible: true,
    prefix: "data-struct/",
    children: [
      "",
      "sort",
      "graph",
    ],
  },
  {
    text: "PAT 甲级",
    collapsible: true,
    prefix: "pat-a/",
    children: [
      "1001-a+b-format.md",
      "1002-a+b-for-polynomialst.md",
      "1003-emergency.md",
      "1004-counting-leaves.md",
      "1005-spell-it-right.md",
      "1006-sign-in-and-sign-out.md",
      "1007-maximum-subsequence-sum.md",
      "1008-elevator.md",
      "1009-product-of-polynomials.md",
      "1010-radix.md",
      "1011-world-cup-betting.md",
      "1012-the-best-rank.md",
      "1013-battle-over-cities.md",
      "1016-phone-bills.md",
      "1018-public-bike-management.md",
      "1020-tree-traversals.md",
      "1021-deepest-root.md",
      "1025-pat-ranking.md",
      "1028-list-sorting.md",
      "1030-travel-plan.md",
      "1034-head-of-a-gang.md",
      "1043-is-it-a-binary-search-tree.md",
      "1053-path-of-equal-weight.md",
      "1062-talent-and-virtue.md",
      "1064-complete-binary-search-tree.md",
      "1066-root-of-avl-tree.md",
      "1069-the-black-hole-of-numbers.md",
      "1076-forwards-on-weibo.md",
      "1079-total-sales-of-supply-chain.md",
      "1086-tree-traversals-again.md",
      "1087-all-roads-lead-to-rome.md",
      "1089-insert-or-merge.md",
      "1090-highest-price-in-supply-chain.md",
      "1093-count-pat's.md",
      "1094-the-largest-generation.md",
      "1098-insertion-or-heap-sort.md",
      "1099-build-a-binary-search-tree.md",
      "1100-mars-numbers.md",
      "1101-quick-sort.md",
      "1102-invert-a-binary-tree.md",
      "1103-integer-factorization.md",
      "1106-lowest-price-in-supply-chain.md",
      "1107-social-clusters.md",
      "1113-integer-set-partition.md",
      "1115-counting-nodes-in-a-bst.md",
      "1116-come-on!-let's-c.md",
      "1117-eddington-number.md",
      "1120-friend-numbers.md",
      "1121-damn-single.md",
      "1122-hamiltonian-cycle.md",
      "1124-raffle-for-weibo-followers.md",
      "1125-chain-the-ropes.md",
      "1126-eulerian-path.md",
      "1127-zigzagging-on-a-tree.md",
      "1128-n-queens-puzzle.md",
      "1130-infix-expression.md",
      "1132-cut-integer.md",
      "1133-splitting-a-linked-list.md",
      "1134-vertex-cover.md",
      "1135-is-it-a-red-black-tree.md",
      "1137-final-grading.md",
      "1138-postorder-traversal.md",
      "1140-look-and-say-sequence.md",
      "1141-pat-ranking-of-institutions.md",
      "1142-maximal-clique.md",
      "1144-the-missing-number.md",
      "1145-hashing-average-search-time.md",
      "1146-topological-order.md",
      "1147-heaps.md",
      "1148-werewolf-simple-version.md",
      "1149-dangerous-goods-packaging.md",
      "1150-travelling-salesman-problem.md",
      "1151-lca-in-a-binary-tree.md",
      "1152-google-recruitment.md",
      "1154-vertex-coloring.md",
      "1155-heap-paths.md",
    ],
  },
  {
    text: "LeetCode Easy",
    collapsible: true,
    prefix: "leetcode-easy/",
    children: [
      '1.md',
      '7.md',
      '9.md',
      '13.md',
      '14.md',
      '20.md',
      '21.md',
      '26.md',
      '27.md',
      '29.md',
      '53.md',
      '58.md',
      '66.md',
      '67.md',
      '69.md',
      '70.md',
      '83.md',
      '88.md',
      '94.md',
      '100.md',
      '101.md',
      '104.md',
      '169.md',
      '1920.md',
      '2525.md',
      '2562.md',
      '2578.md',
    ],
  },
  {
    text: "LeetCode Medium",
    collapsible: true,
    prefix: "leetcode-medium/",
    children: [
      '2.md',
      '3.md',
      '5.md',
      '6.md',
      '8.md',
      '11.md',
      '12.md',
      '15.md',
      '16.md',
      '17.md',
      '18.md',
      '19.md',
      '22.md',
      '24.md',
      '28.md',
      '33.md',
      '35.md',
      '61.md',
      '80.md',
      '82.md',
      '92.md',
      '96.md',
      '102.md',
      '105.md',
      '106.md',
      '107.md',
      '147.md',
      '189.md',
      '207.md',
      '721.md',
      '1488.md',
      '2316.md',
      '2512.md',
    ],
  },
  {
    text: "LeetCode Hard",
    collapsible: true,
    prefix: "leetcode-hard/",
    children: [
      '4.md',
      '10.md',
      '23.md',
      '25.md',
    ],
  },
  {
    text: "LeetCode 周赛",
    collapsible: true,
    prefix: "leetcode-weekly-contest/",
    children: [
      '83.md',
      '367.md',
    ],
  },
  {
    text: "LeetCode SQL",
    collapsible: true,
    prefix: "leetcode-sql/",
    children: [
      '175.md',
      '176.md',
      '177.md',
      '178.md',
      '180.md',
      '181.md',
      '182.md',
      '184.md',
    ],
  },
  "leet-code-tag",
]);
