before_script:
  - echo $CI_PIPELINE_SOURCE

lint:
  script: echo "lint..."
  only:
    refs:
      - merge_requests

deploy:
  stage: deploy
  only:
    - develop
  script:
    - echo $(git diff-tree --name-only -r $CI_COMMIT_BEFORE_SHA HEAD)
