type: google.api.Service
config_version: 3

http:
  rules:
    - selector: gw.k8s.KubernetesService.ListNamespaces
      post: "/v0/mix/k8s/namespaces"
      body: '*'
    - selector: gw.k8s.KubernetesService.ListResources
      post: "/v0/mix/k8s/resources"
      body: '*'
    - selector: gw.k8s.KubernetesService.RolloutRestartDeployment
      post: "/v0/mix/k8s/deployment/restart"
      body: '*'
