version: '3.8'
services:
  bark-server:
    image: finab/bark-server
    container_name: bark-server
    restart: always
    volumes:
      - /root/apps/bark/data:/data
    ports:
      - "8180:8080"

# https://github.com/Finb/bark-server/issues/175
