---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis6-single
  name: redis6-single
  namespace: alomerry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  volumeMode: Filesystem
  storageClassName: nfs-csi
---

