---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis6-s
  name: redis-pvc-s
  namespace: alomerry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M
  volumeMode: Filesystem
  storageClassName: nfs-csi
---