- name: install dependence
  include_tasks: common.yml
- name: init frps
  include_tasks: init.yml
- name: setup frps
  include_tasks: setup.yml
- name: enable and start frps service
  shell: |
    systemctl enable frps.service
    systemctl stop frps.service
    systemctl daemon-reload
    systemctl start frps.service