---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hertzbeat-cluster-admin
  namespace: hertzbeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hertzbeat-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: hertzbeat-cluster-admin
  namespace: hertzbeat
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: hertzbeat-cluster-admin
  name: hertzbeat-cluster-token
  namespace: hertzbeat
type: kubernetes.io/service-account-token
# k describe secret -n hertzbeat hertzbeat-cluster-token 