- name: init dozzle workspace
  shell: |
    mkdir /root/apps/dozzle/ -p
- name: copy docker compose
  copy:
    src: dozzle.yml
    dest: /root/apps/dozzle/docker-compose.yml
- name: update dozzle image
  shell: /usr/bin/docker compose -f /root/apps/dozzle/docker-compose.yml pull
- name: run dozzle
  shell: /usr/bin/docker compose -f /root/apps/dozzle/docker-compose.yml up -d --force-recreate
