- name: check alomerry.dev cert exists
  ansible.builtin.stat:
    path: "/root/.acme.sh/alomerry.dev_ecc"
  register: basedir_stat
- name: check and generate cloudflare ssl
  shell: |
    /root/.acme.sh/acme.sh --issue --dns dns_cf -d alomerry.dev
  when: not basedir_stat.stat.exists
- name: renew cloudflare ssl
  shell: |
    /root/.acme.sh/acme.sh --renew -d alomerry.dev
  when: basedir_stat.stat.exists
- name: install cloudflare ssl
  shell: |
    /root/.acme.sh/acme.sh --install-cert -d alomerry.dev --key-file /root/apps/nginx/cert/{{ item }}/privkey.pem --fullchain-file /root/apps/nginx/cert/{{ item }}/fullchain.pem
  with_items:
    - bark.alomerry.dev
    - ci.alomerry.dev
    - umami.alomerry.dev
    - uptime.alomerry.dev
    - waline.alomerry.dev