apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: alomerry
spec:
  ports:
  - name: redis-port
    port: 6379
    targetPort: redis-port
  selector:
    app: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-config: |
    port 6379
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /root/apps/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - node1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: alomerry
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: alomerry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:7.2.1
        name: redis
        command:
        - redis-server
        - "/redis-master/redis.conf"
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - name: redis-config
          mountPath: /redis-master
        - name: redis-pv
          mountPath: /redis-master-data
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
          items:
          - key: redis-config
            path: redis.conf
      - name: redis-pv
        persistentVolumeClaim:
          claimName: redis-pvc

# https://github.com/Lancger/opsfull/blob/master/redis/K8s%E4%B8%8A%E8%BF%90%E8%A1%8CRedis%E9%9B%86%E7%BE%A4%E6%8C%87%E5%8D%97.md