- name: check frps exists
  ansible.builtin.stat:
    path: "/root/apps/frps/{{FRP_VERSION}}.version"
  register: basedir_stat
- name: init frps workspace
  shell: rm -rf /root/apps/frps
  when: not (basedir_stat.stat.exists)
- name: download frps bin
  shell: |
    mkdir /root/apps/frps -p
    wget -P /root/apps/frps https://ghproxy.com/https://github.com/fatedier/frp/releases/download/v{{FRP_VERSION}}/frp_{{FRP_VERSION}}_linux_amd64.tar.gz -O /root/apps/frps/frps.tar.gz
  when: not (basedir_stat.stat.exists)
- name: extract frp tar
  shell: tar -xf /root/apps/frps/frps.tar.gz --strip-components 1 -C /root/apps/frps/
  when: not (basedir_stat.stat.exists)
- name: clean cache
  shell: |
    rm -rf /root/apps/frps/frps.tar.gz 
    rm -rf /root/apps/frps/frpc
    rm -rf /root/apps/frps/frpc_full.ini 
    rm -rf /root/apps/frps/frps_full.ini
    rm -rf /root/apps/frps/frpc.ini
- name: set frpc version
  shell: touch /root/apps/frps/{{FRP_VERSION}}.version
  when: not (basedir_stat.stat.exists)