---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-5-pvc-alomerry
  namespace: alomerry
spec:
  resources:
    requests:
      storage: 10G
  volumeMode: Filesystem
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-5-service
  namespace: alomerry
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-5-deployment
  namespace: alomerry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql5
    spec:
      containers:
        - image: mysql:5.7
          name: mysql5
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: rootPasswd_5
            - name: MYSQL_ROOT_HOST
              value: ""
          ports:
            - containerPort: 3306
              protocol: TCP
              name: mysql
          volumeMounts:
            - name: localtime
              readOnly: true
              mountPath: /etc/localtime
            - name: mysql-5-pv
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-5-pv
          persistentVolumeClaim:
            claimName: mysql-5-pvc-alomerry
        - name: localtime
          hostPath:
            type: File
            path: /etc/localtime
