---
- hosts: tencent-cvm
  tasks:
    - name: test connection
      ping:
      remote_user: ubuntu
    - name: disable selinux
      command: /sbin/setenforce 0
    - name: stop unattended-upgrades
      shell: |
        if [[ $(systemctl is-active unattended-upgrades) == "active" ]]; then
          systemctl stop unattended-upgrades
        fi
      args:
        executable: /bin/bash