- hosts: local
  remote_user: root
  vars:
    - FRP_VERSION: 0.51.3
    - ENV: LOCAL
  roles:
    - frpc
    # - common
    # - bark
    # - aliyun
    # - docker
    # - jenkins
    # - mysql
    # - umami
    # - uptime
    # - bark
    # - waline
