version: '3'
services:
  jenkins:
    image: 'jenkinsci/blueocean:1.25.7'
    container_name: jenkins-blueocean
    user: root
    restart: always
    ports: 
      - '880:8080'
    volumes:
      - '/home/alomerry-home/apps/jenkins:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
