apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-docs
spec:
  params:
  - name: repo-url
    type: string
  workspaces:
  - name: ssh-creds
  - name: shared-data
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone 
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: build-frontend
    runAfter: [ "fetch-source" ]
    taskRef:
      name: build-frontend
    workspaces:
      - name: source
        workspace: shared-data
  - name: deploy-frontend
    runAfter: [ "build-frontend" ]
    taskRef:
      name: rsync
    params:
      - name: direction
        value: "local-to-remote"
      - name: local-path
        value: "./docs/.vitepress/dist/"
      - name: remote-ip
        value: "proxy.alomerry.com"
      - name: remote-username
        value: "root"
      - name: remote-path
        value: "/root/apps/nginx/site/docs.alomerry.com/"
    workspaces:
      - name: source
        workspace: shared-data
      - name: ssh-directory
        workspace: ssh-creds
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc-docs
spec:
  selector:
    matchLabels:
      service: tekton
      project: docs
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce