apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: docs-deploy-
spec:
  pipelineRef:
    name: deploy-docs
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: ssh-creds
    secret:
      secretName: rsync-ssh-credentials
  - name: shared-data
    persistentVolumeClaim:
      claimName: tekton-pvc-docs
  params:
  - name: repo-url
    value: https://github.com/alomerry/mix.git
