---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-app
  namespace: apinto
spec:
  serviceName: "redis-service"
  replicas: 6
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: redis
        image: docker.eolinker.com/docker/redis:6.2.7
        command:
          - "redis-server"
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        args:
          - "/etc/redis/redis.conf"
          - "--protected-mode"
          - "no"
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        volumeMounts:
          - name: "redis-conf"
            mountPath: "/etc/redis"
          - name: "redis-data"
            mountPath: "/var/lib/redis"
      imagePullSecrets:
      - name: docker-eolinker
      volumes:
      - name: "redis-conf"
        configMap:
          name: "redis-conf"
          items:
            - key: "redis.conf"
              path: "redis.conf"
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200M
  selector:
    matchLabels:
      app: redis-app