---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: apinto
  labels:
    app: redis-app
spec:
  ports:
  - name: redis-port
    port: 6379
  selector:
    app: redis-app
---
apiVersion: v1
kind: Service
metadata:
  name: redis-access-service
  namespace: apinto
  labels:
    app: redis-app
spec:
  ports:
  - name: redis-port
    protocol: "TCP"
    port: 6379
    targetPort: 6379
  selector:
    app: redis-app
    
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: influxdb
  name: influxdb
  namespace: apinto
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: influx
      nodePort: 31086
      port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    k8s.kuboard.cn/name: influxdb
  sessionAffinity: None
  type: NodePort
  
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: apinto-dashboard
  name: apinto-dashboard
  namespace: apinto
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: service
      nodePort: 31190
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    k8s.kuboard.cn/name: apinto-dashboard
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s.kuboard.cn/name: apinto-depend
  name: apinto-depend
  namespace: apinto
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: user-center
      port: 19007
      protocol: TCP
      targetPort: 19007
  selector:
    k8s.kuboard.cn/name: apinto-depend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: apinto-plugin
  name: apinto-plugin
  namespace: apinto
spec:
  ports:
    - name: apinto-monitor
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: apinto-user-center
      port: 9080
      protocol: TCP
      targetPort: 9080
  selector:
    k8s.kuboard.cn/name: apinto-plugin
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: apinto-gateway-stateful
  name: apinto-gateway-stateful
  namespace: apinto
spec:
  ports:
    - name: http
      nodePort: 31189
      port: 8099
      protocol: TCP
      targetPort: 8099
    - name: admin
      nodePort: 31194
      port: 9400
      protocol: TCP
      targetPort: 9400
    - name: cluster
      nodePort: 31191
      port: 9401
      protocol: TCP
      targetPort: 9401
  type: NodePort
  selector:
    k8s.kuboard.cn/name: apinto-gateway-stateful