- name: 复制 kubelet 安装脚本
  copy:
    src: install/kubelet.sh
    dest: /tmp/kubelet.sh
    mode: 0744
- shell: "/tmp/kubelet.sh {{ k8s.version}}"
- name: copy kubelet service
  copy:
    src: "kubelet/kubelet-v{{k8s.elet_service_version}}.service"
    dest: /etc/systemd/system/kubelet.service