version: '3'
services:
  ddns-go:
    image: jeessy/ddns-go
    environment:
      - f=180
      - cacheTimes=20
    # ports:
    #   - "9876:9876"
    network_mode: "host"
    volumes:
      - './config:/root'
    restart: always
