- name: init mysql workspace
  shell: |
    mkdir /root/apps/mysql/ -p
- name: copy docker compose
  copy:
    src: mysql.yml
    dest: /root/apps/mysql/docker-compose.yml
- name: copy .env
  copy:
    src: .env
    dest: /root/apps/mysql/.env
- name: stop and restart mysql # TODO add pull /usr/bin/docker compose -f /root/apps/jenkins/docker-compose.yml build
  shell: |
    /usr/bin/docker compose -f /root/apps/mysql/docker-compose.yml down
    /usr/bin/docker compose -f /root/apps/mysql/docker-compose.yml up -d
