- name: check frps exists
  ansible.builtin.stat:
    path: "{{frp.version}}{{frp.frpsPath}}.version"
  register: frps_check
- shell: rm -rf /root/apps/frps
  when: not (frps_check.stat.exists)
- include_task: debs.yml
  when: not (frps_check.stat.exists)
- name: install frps
  include_tasks: install.yml
  when: not (frps_check.stat.exists)
- include_tasks: clean.yml
- include_tasks: setup.yml
- shell: |
    systemctl enable frps.service
    systemctl stop frps.service
    systemctl daemon-reload
    systemctl start frps.service