- name: add docker apt key
  apt_key:
    url: http://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg
    state: present
- name: add docker apt source list
  apt_repository:
    repo: 'deb [arch=amd64] http://mirrors.aliyun.com/docker-ce/linux/ubuntu focal stable'
    state: present
- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: install docker
  apt:
    name:
    - docker-ce=v24.0.5
    - docker-ce-cli=v2.20.2
    - containerd.io={{ k8s.containerdVersion }}