---
apiVersion: v1
kind: Service
metadata:
  name: mix-module-blog-service
  namespace: alomerry
spec:
  ports:
    - name: http
      port: 8091
      targetPort: http
      protocol: TCP
  selector:
    app: mix-module-blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mix-module-blog-deployment
  namespace: alomerry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mix-module-blog
  template:
    metadata:
      labels:
        app: mix-module-blog
        log: "true"
    spec:
      containers:
        - name: mix-module-blog
          image: registry.cn-hangzhou.aliyuncs.com/alomerry/mix-blog:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          env:
            - name: ELASTICSEARCH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: mix-secret
                  key: es-endpoint
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mix-secret
                  key: es-search-blog-api
