---
apiVersion: v1
kind: Service
metadata:
  name: mix-module-k8s-service
  namespace: alomerry
spec:
  ports:
    - name: http
      port: 8091
      targetPort: http
      protocol: TCP
  selector:
    app: mix-module-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mix-module-k8s-deployment
  namespace: alomerry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mix-module-k8s
  template:
    metadata:
      labels:
        app: mix-module-k8s
        log: "true"
    spec:
      containers:
        - name: mix-module-k8s
          image: registry.cn-hangzhou.aliyuncs.com/alomerry/mix-k8s:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mix-rw-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "persistentvolumeclaims", "namespaces", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mix-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mix-rw-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: alomerry
---