apiVersion: v1
kind: Namespace
metadata:
  name: mix
---
apiVersion: v1
kind: Service
metadata:
  name: gw-service
  namespace: mix
spec:
  ports:
    - name: http
      port: 4790
      targetPort: http
      protocol: TCP
  selector:
    app: gw-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-deployment
  namespace: mix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw-pod
  template:
    metadata:
      labels:
        app: gw-pod
    spec:
      containers:
        - name: gw-pod
          image: registry.cn-hangzhou.aliyuncs.com/alomerry/gw:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4790
              protocol: TCP
          env:
          - name: ELASTICSEARCH_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: mix-secret
                key: es-endpoint
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mix-secret
                key: es-search-blog-api