apiVersion: v1
kind: Namespace
metadata:
  name: mix
---
apiVersion: v1
kind: Service
metadata:
  name: gw-service
  namespace: mix
spec:
  ports:
    - name: http
      port: 4790
      targetPort: http
      protocol: TCP
  selector:
    app: gw-pod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: mix
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gw-rw-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "persistentvolumeclaims", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mix-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gw-rw-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: mix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-deployment
  namespace: mix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw-pod
  template:
    metadata:
      labels:
        app: gw-pod
        log: "true"
    spec:
      containers:
        - name: gw-pod
          image: registry.cn-hangzhou.aliyuncs.com/alomerry/gw:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4790
              protocol: TCP
          env:
          - name: ELASTICSEARCH_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: mix-secret
                key: es-endpoint
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mix-secret
                key: es-search-blog-api
          - name: MYSQL_ADMIN_DSN
            valueFrom:
              secretKeyRef:
                name: mix-secret
                key: home-lab-admin-mysql-dsn
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: mix-secret
                key: home-lab-admin-token-secret
          - name: DATABASE_SALT
            valueFrom:
              secretKeyRef:
                name: mix-secret
                key: database-salt