- name: 检查 docker 是否存在
  shell: docker -v
  register: docker_check
  ignore_errors: true
- name: 添加 docker 官方 GPG key
  shell: install -m 0755 -d /etc/apt/keyrings && rm -rf /etc/apt/keyrings/docker.gpg && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && chmod a+r /etc/apt/keyrings/docker.gpg
  when: docker_check.rc != 0
- name: 设置 docker 仓库
  shell: |
    echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: docker_check.rc != 0
- name: 更新 apt 库
  shell: apt-get update
  when: docker_check.rc != 0
- name: 安装 docker # 检查以下包是否全部要安装，k8s 最新版已经不依赖 docker 了
  apt:
    name: '{{ item }}'
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  when: docker_check.rc != 0
# TODO set docker version locked