- name: containerd
  include_tasks: container/main.yml
# - name: set common app
#   include_tasks: debs/main.yml
# - name: set kubectl
#   include_tasks: kubectl/main.yml
# - name: set kubeadm
#   include_tasks: kubeadm/main.yml
- name: set kubelet
  include_tasks: kubelet/main.yml
- name: enable kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
    state: started
# - name: set helm
#   include_tasks: helm.yml
# - name: set cni
#   include_tasks: cni/main.yml
# - name: init preset
#   include_tasks: init-preset.yml

https://github.com/containerd/containerd/issues/8139