- name: init blog.alomerry.com workspace
  shell: |
    mkdir /root/apps/nginx/site/blog.alomerry.com/ -p
    mkdir /root/apps/nginx/cert/blog.alomerry.com/ -p
    mkdir /root/apps/nginx/conf/blog.alomerry.com/ -p
    touch /root/apps/nginx/cert/blog.alomerry.com/privkey.pem
    touch /root/apps/nginx/cert/blog.alomerry.com/fullchain.pem
- name: copy nginx conf
  copy:
    src: conf/blog.conf
    dest: /root/apps/nginx/conf/blog.alomerry.com.conf
# - name: generate ssl
#   shell: /root/.acme.sh/acme.sh --issue --dns dns_ali -d blog.alomerry.com --webroot /root/apps/nginx/site/blog.alomerry.com/ --nginx
- name: install ssl
  shell: /root/.acme.sh/acme.sh --install-cert -d blog.alomerry.com --key-file /root/apps/nginx/cert/blog.alomerry.com/privkey.pem --fullchain-file /root/apps/nginx/cert/blog.alomerry.com/fullchain.pem --reloadcmd "service nginx force-reload"
