- name: generate and install cloudflare ssl
  shell: |
    /root/.acme.sh/acme.sh --issue --dns dns_cf -d {{ item }} --webroot /root/apps/nginx/site/{{ item }}/ --nginx
    /root/.acme.sh/acme.sh --install-cert -d {{ item }} --key-file /root/apps/nginx/cert/{{ item }}/privkey.pem --fullchain-file /root/apps/nginx/cert/{{ item }}/fullchain.pem
  with_items: 
    - bark.alomerry.dev
    - ci.alomerry.dev
    - umami.alomerry.dev
    - uptime.alomerry.dev
    - waline.alomerry.dev
