apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: docs-deploy-
spec:
  selector:
    project: docs
  pipelineRef:
    name: deploy-mix
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: ssh-creds
    secret:
      secretName: rsync-ssh-credentials
  - name: shared-data
    persistentVolumeClaim:
      claimName: tekton-pvc-docs
  params:
  - name: repo-url
    value: https://gitee.com/alomerry/mix.git
  - name: mix-module
    value: docs
  - name: build-output-path
    value: docs/.vitepress/dist/
