apiVersion: v1
kind: Namespace
metadata:
  name: alomerry
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    service: mysql
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /mnt/nvme0n1p1/mysql
    server: 192.168.31.2
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: alomerry
spec:
  selector:
    matchLabels:
      service: mysql
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce