apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: docs
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: docs
  source:
   repoURL: https://gitee.com/alomerry/mix.git
    targetRevision: master
    path: .gitops/frontend/docs.yml
  sources: []
  project: 'mix'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true