apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mix
  namespace: argocd
spec:
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://gitee.com/alomerry/mix.git