- name: copy install script
  copy:
    src: install/kubeadm.sh
    dest: /tmp/kubeadm.sh
    mode: 0744
- shell: "/tmp/kubeadm.sh {{ k8s.version}}"
- name: copy init config
  copy:
    src: "kubeadm/init.yml"
    dest: /var/lib/kubelet/config.yaml
- name: copy kubeadm config
  copy:
    src: "kubeadm/kubeadm.conf"
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf