- name: set k8s-master conf
  copy:
    src: master
    dest: /root/apps/frpc/
- name: set k8s-master frpc service
  copy:
    src: frp-master.service
    dest: /etc/systemd/system/frp-master.service
- name: enable and start frp-master frpc service
  shell: |
    systemctl enable frp-master.service
    systemctl stop frp-master.service