---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis6-alomerry
  namespace: alomerry
spec:
  serviceName: "redis-service-alomerry"
  replicas: 6
  selector:
    matchLabels:
      app: redis6
  template:
    metadata:
      labels:
        app: redis6
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: redis
        image: redis:6.2.7
        command:
          - "redis-server"
        args:
          - "/etc/redis/redis.conf"
          - "--protected-mode"
          - "no"
        ports:
          - name: redis
            containerPort: 6379
            protocol: "TCP"
        resources:
          requests:
            cpu: "100m"
            memory: "1024Mi"
        volumeMounts:
          - name: "redis-conf"
            mountPath: "/etc/redis"
          - name: "redis-pvc"
            mountPath: "/var/lib/redis"
      volumes:
      - name: "redis-conf"
        configMap:
          name: "redis-conf-alomerry"
          items:
            - key: "redis.conf"
              path: "redis.conf"
  volumeClaimTemplates:
  - metadata:
      name: redis-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nfs-csi
      resources:
        requests:
          storage: 200M
---

# ```shell
# redis-cli --cluster create \
# `dig +short redis6-alomerry-0.redis-service-alomerry.alomerry.svc.cluster.local`:6379 \
# `dig +short redis6-alomerry-1.redis-service-alomerry.alomerry.svc.cluster.local`:6379 \
# `dig +short redis6-alomerry-2.redis-service-alomerry.alomerry.svc.cluster.local`:6379 \
# `dig +short redis6-alomerry-3.redis-service-alomerry.alomerry.svc.cluster.local`:6379 \
# `dig +short redis6-alomerry-4.redis-service-alomerry.alomerry.svc.cluster.local`:6379 \
# `dig +short redis6-alomerry-5.redis-service-alomerry.alomerry.svc.cluster.local`:6379 \
# --cluster-replicas 1 -a 密码
# ```