version: "3.3"
services:
  web:
    # build:
    #   context: .
    #   args:
    #     ENABLED_MODULES: rtmp
    image: registry.cn-hangzhou.aliyuncs.com/alomerry/nginx-with-rtmp
    ports:
      - "1935:1935"
    volumes:
      - './data/nginx.conf:/etc/nginx/nginx.conf'