- name: install common debs
  apt:
    name: '{{ item }}'
  with_items:
  - tree
  - curl
  - wget
  - net-tools
  - zsh
  - git
  - dnsutils
  - iputils-ping
- name: set docker
  include_tasks: docker.yml
- name: set oh-my-zsh
  include_tasks: zsh.yml