name: deploy blog to vps

on:
  push:
    branches: [master]
    paths:
      - "pages/**"
      - "src/**"
      - ".github/workflows/build-deploy.yml"

jobs:
  build-deploy-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v3
        with:
          version: 9.1.1
          run_install: true
      - name: build blog
        run: |
          pnpm install && pnpm build
          tar -zcvf res.tar.gz -C ./dist/ .
      - name: scp dist
        uses: appleboy/scp-action@v0.1.7
        with:
          host: blog.alomerry.com
          username: root
          key: ${{ secrets.VPS_SECRET_SSH_KEY }}
          port: ${{ vars.VPS_SSH_PORT }}
          source: "res.tar.gz"
          target: "/tmp/"
      - name: deploy blog
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: blog.alomerry.com
          username: root
          key: ${{ secrets.VPS_SECRET_SSH_KEY }}
          port: ${{ vars.VPS_SSH_PORT }}
          script: |
            rm -rf /root/apps/nginx/site/blog.alomerry.com/*
            tar -zxvf /tmp/res.tar.gz -C /root/apps/nginx/site/blog.alomerry.com/;
            rm /tmp/res.tar.gz