name: dst-admin-go

on:
  push:
    branches:
      - master
    paths:
      - vm/docker/apps/dst-admin/*
      - .github/workflows/dst-admin-go.yml

env:
  BUILD_VERSION: "git"
  OPENSSL_VERSION: "3.0.0"
  PCRE_VERSION: "8.45"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/${{ github.workflow }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 构建镜像推送到 aliyun
        run: |
          docker version
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          cd vm/docker/apps/dst-admin
          
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/alomerry/dst-admin:latest
          docker push registry.cn-hangzhou.aliyuncs.com/alomerry/dst-admin:latest
