name: deploy blog to vps

on:
  push:
    branches: [master]
    paths:
      - "blog/pages/**"
      - "blog/src/**"
      - ".github/workflows/frontend-blog.yml"

jobs:
  build-deploy-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.6
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH_BLOG=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH_BLOG }}
          key: ${{ runner.os }}-pnpm-store-blog-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-blog-
      - name: build blog
        run: |
          cd blog
          pnpm install && pnpm build
          tar -zcvf res.tar.gz -C ./dist/ .
      - name: scp dist
        uses: appleboy/scp-action@v0.1.7
        with:
          host: blog.alomerry.com
          username: root
          key: ${{ secrets.VPS_SECRET_SSH_KEY }}
          port: ${{ vars.VPS_SSH_PORT }}
          source: "blog/res.tar.gz"
          target: "/tmp/"
      - name: deploy blog
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: blog.alomerry.com
          username: root
          key: ${{ secrets.VPS_SECRET_SSH_KEY }}
          port: ${{ vars.VPS_SSH_PORT }}
          script: |
            rm -rf /root/apps/nginx/site/blog.alomerry.com/*
            tar -zxvf /tmp/blog/res.tar.gz -C /root/apps/nginx/site/blog.alomerry.com/;
            rm /tmp/blog/res.tar.gz
