name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: { branches: ["master"]  }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Main
        uses: lowlighter/metrics@latest
        with:
          filename: .github/metrics/classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: .github/metrics/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: .github/metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, yaml,
            gnuplot