name: 构建 openapi 服务 docker 镜像并发送到 aliyun

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/openapi-gw.yml"
      - "golang/gw/openapi/**"
      - "golang/gw/proto/**"
      - "golang/gw/Dockerfile"
      - "golang/gw/build.sh"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'
      - name: 安装 protoc-gen-go/grpc/grpc-gateway/openapiv2 插件
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.18
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.18
      - name: 生成桩文件
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          cd golang/gw
          ./build.sh proto
          ./build.sh gateway
      - name: 构建二进制
        run: |
          cd golang/gw
          go build -o gw openapi/main.go
      - name: 构建镜像
        run: |
          docker version
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          cd golang/gw
          chmod +x ./gw
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/alomerry/mix-gw:latest
          docker push registry.cn-hangzhou.aliyuncs.com/alomerry/mix-gw:latest
      # https://github.com/marketplace/actions/http-request-action
      # - name: trigger rollout restart
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: ${{secrets.MIX_GW_RESTART_URL}}
      #     method: "POST"
