name: build blog search idx after pages changed

on:
  push:
    branches: [ master ]
    paths:
      - 'blog/pages/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'
      - name: build gw bin
        env:
          ELASTICSEARCH_ENDPOINT: ${{ secrets.ELASTICSEARCH_ENDPOINT }}
          ELASTICSEARCH_PASSWORD: ${{ secrets.ELASTICSEARCH_PASSWORD }}
        run: |
          cd golang/mix-tools
          go run main.go -e "${{env.ELASTICSEARCH_ENDPOINT}}" "${{env.ELASTICSEARCH_PASSWORD}}"
        # https://programmercave.com/blog/2023/08/03/Step-by-Step-Guide-Setting-up-Environment-Variables-in-GitHub-Actions-for-Go
