---
apiVersion: v1
kind: Namespace
metadata:
  name: waline
---
apiVersion: v1
kind: Service
metadata:
  name: waline-blog-service
  namespace: waline
spec:
  ports:
  - name: waline
    port: 8360
    targetPort: waline
    protocol: TCP
  selector:
    app: waline-blog